import React from 'react';
import { View, Text, ScrollView, StyleSheet } from 'react-native';

export default function NutritionScreen() {
  return (
    <ScrollView contentContainerStyle={{ padding: 16 }}>
      <View style={styles.container}>
        <Text style={{ color: '#111827' }}>Nutrition screen booted ✅</Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f5' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#e0e0e0' },
  headerTitle: { fontSize: 24, fontWeight: 'bold', color: '#065f46' },
  historyButton: { paddingHorizontal: 16, paddingVertical: 8, backgroundColor: '#3F6B5C', borderRadius: 8 },
  historyButtonText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  targetsCard: { marginHorizontal: 16, marginTop: 16 },
  macrosRow: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 16 },
  macroItem: { alignItems: 'center' },
  macroValue: { fontSize: 18, fontWeight: 'bold', color: '#065f46' },
  macroLabel: { fontSize: 12, color: '#6b7280', marginTop: 4 },
  remainingRow: { flexDirection: 'row', justifyContent: 'space-around', paddingTop: 12, borderTopWidth: 1, borderTopColor: '#e5e7eb' },
  remainingItem: { alignItems: 'center' },
  remainingValue: { fontSize: 16, fontWeight: '600', color: '#059669' },
  overTarget: { color: '#dc2626' },
  remainingLabel: { fontSize: 11, color: '#6b7280', marginTop: 2 },
  content: { flex: 1 },
  contentContainer: { padding: 16, gap: 12 },
  mealEmoji: { fontSize: 24 },
  logButton: { backgroundColor: '#3F6B5C', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 6 },
  logButtonText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  mealMacros: { flexDirection: 'row', justifyContent: 'space-around', gap: 8 },
  mealMacroText: { fontSize: 12, color: '#374151' },
  emptyText: { textAlign: 'center', color: '#9ca3af', fontSize: 14, paddingVertical: 20 },
  actionButtons: { flexDirection: 'row', gap: 8 },
  editButton: { backgroundColor: '#3F6B5C', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6 },
  editButtonText: { color: '#fff', fontSize: 11, fontWeight: '600' },
  copyButton: { backgroundColor: '#059669', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6 },
  copyButtonText: { color: '#fff', fontSize: 11, fontWeight: '600' },
  foodsList: { marginBottom: 12 },
  foodItem: { marginBottom: 8 },
  foodName: { fontSize: 13, fontWeight: '600', color: '#1f2937', marginBottom: 2 },
  foodDetails: { fontSize: 11, color: '#6b7280', marginLeft: 12 },
  historyMacros: { flexDirection: 'row', justifyContent: 'space-around', paddingTop: 8, borderTopWidth: 1, borderTopColor: '#e5e7eb' },
  historyMacroText: { fontSize: 11, color: '#374151', fontWeight: '500' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: '90%', paddingBottom: 20 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
  modalTitle: { fontSize: 18, fontWeight: 'bold', color: '#065f46' },
  closeButton: { fontSize: 28, color: '#6b7280', lineHeight: 28 },
  stagedSection: { padding: 16, backgroundColor: '#f0fdf4', borderBottomWidth: 1, borderBottomColor: '#d1fae5' },
  stagedTitle: { fontSize: 14, fontWeight: '600', color: '#065f46', marginBottom: 8 },
  stagedFoodsScroll: { maxHeight: 200 },
  stagedFood: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#fff', padding: 10, borderRadius: 8, marginBottom: 8, borderWidth: 1, borderColor: '#d1fae5' },
  stagedFoodInfo: { flex: 1 },
  stagedFoodName: { fontSize: 13, fontWeight: '600', color: '#065f46', marginBottom: 2 },
  stagedFoodMacros: { fontSize: 11, color: '#6b7280' },
  removeButton: { marginLeft: 8, padding: 4 },
  removeButtonText: { fontSize: 18, color: '#dc2626', fontWeight: 'bold' },
  stagedTotals: { marginTop: 8, paddingTop: 8, borderTopWidth: 1, borderTopColor: '#d1fae5' },
  stagedTotalText: { fontSize: 12, fontWeight: '600', color: '#065f46', textAlign: 'center' },
  modalScroll: { maxHeight: 400 },
  searchSection: { padding: 16 },
  searchInput: { borderWidth: 1, borderColor: '#d1d5db', borderRadius: 8, padding: 12, fontSize: 14, backgroundColor: '#fff' },
  searchLoader: { marginTop: 12 },
  resultsSection: { paddingHorizontal: 16 },
  resultItem: { backgroundColor: '#fff', padding: 12, borderRadius: 8, marginBottom: 8, borderWidth: 1, borderColor: '#e5e7eb' },
  resultName: { fontSize: 14, fontWeight: '500', color: '#1f2937', marginBottom: 2 },
  resultServing: { fontSize: 12, color: '#6b7280' },
  manualEntryButton: { margin: 16, padding: 14, backgroundColor: '#f3f4f6', borderRadius: 8, borderWidth: 1, borderColor: '#d1d5db', borderStyle: 'dashed' },
  manualEntryButtonText: { textAlign: 'center', color: '#3F6B5C', fontSize: 14, fontWeight: '600' },
  manualEntryForm: { padding: 16 },
  manualEntryTitle: { fontSize: 16, fontWeight: 'bold', color: '#065f46', marginBottom: 12 },
  input: { borderWidth: 1, borderColor: '#d1d5db', borderRadius: 8, padding: 12, marginBottom: 12, fontSize: 14, backgroundColor: '#fff' },
  manualButtonsRow: { flexDirection: 'row', gap: 12, marginTop: 8 },
  cancelButton: { flex: 1, padding: 14, backgroundColor: '#f3f4f6', borderRadius: 8, borderWidth: 1, borderColor: '#d1d5db' },
  cancelButtonText: { textAlign: 'center', color: '#6b7280', fontSize: 14, fontWeight: '600' },
  addButton: { flex: 1, padding: 14, backgroundColor: '#3F6B5C', borderRadius: 8 },
  addButtonText: { textAlign: 'center', color: '#fff', fontSize: 14, fontWeight: '600' },
  doneButton: { margin: 16, padding: 16, backgroundColor: '#3F6B5C', borderRadius: 8, alignItems: 'center' },
  doneButtonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  quantityModalContent: { backgroundColor: '#fff', borderRadius: 16, padding: 24, width: '90%', maxWidth: 400 },
  quantityModalTitle: { fontSize: 18, fontWeight: '600', color: '#24534A', marginBottom: 16, textAlign: 'center' },
  servingOptionsContainer: { marginBottom: 20 },
  servingOptionsLabel: { fontSize: 14, fontWeight: '500', color: '#374151', marginBottom: 8 },
  servingOptions: { maxHeight: 100 },
  servingOptionsContent: { paddingHorizontal: 12, paddingVertical: 8, gap: 8, flexDirection: 'row' },
  servingOption: { backgroundColor: '#fff', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 8, alignItems: 'center', borderWidth: 2, borderColor: '#e5e7eb', minWidth: 120 },
  servingOptionSelected: { backgroundColor: '#f0fdf4', borderColor: '#3F6B5C' },
  servingOptionText: { fontSize: 14, fontWeight: '500', color: '#374151' },
  servingOptionTextSelected: { color: '#3F6B5C', fontWeight: '600' },
  servingOptionWeight: { fontSize: 11, color: '#666', marginTop: 2 },
  quantityInputContainer: { marginBottom: 20 },
  quantityInputLabel: { fontSize: 14, fontWeight: '500', color: '#374151', marginBottom: 8 },
  quantityModalInput: { backgroundColor: '#f3f4f6', padding: 16, borderRadius: 8, fontSize: 20, textAlign: 'center', fontWeight: '600' },
  quantityPreview: { backgroundColor: '#f0fdf4', padding: 12, borderRadius: 8, marginBottom: 20 },
  quantityPreviewText: { fontSize: 12, color: '#065f46', textAlign: 'center' },
  quantityModalButtons: { flexDirection: 'row', gap: 12 },
  quantityModalButton: { flex: 1, paddingVertical: 14, borderRadius: 8, alignItems: 'center' },
  quantityCancelButton: { backgroundColor: '#f3f4f6' },
  quantityCancelButtonText: { color: '#374151', fontWeight: '600', fontSize: 16 },
  quantityDoneButton: { backgroundColor: '#3F6B5C' },
  quantityDoneButtonText: { color: '#fff', fontWeight: '600', fontSize: 16 },
  copyPickerContent: { backgroundColor: '#fff', margin: 20, borderRadius: 12, padding: 20 },
  copyPickerTitle: { fontSize: 16, fontWeight: 'bold', color: '#065f46', marginBottom: 16, textAlign: 'center' },
  copyPickerOption: { flexDirection: 'row', alignItems: 'center', padding: 14, backgroundColor: '#f9fafb', borderRadius: 8, marginBottom: 10 },
  copyPickerEmoji: { fontSize: 24, marginRight: 12 },
  copyPickerText: { fontSize: 15, color: '#1f2937', fontWeight: '500' },
  copyPickerCancel: { marginTop: 8, padding: 14, backgroundColor: '#f3f4f6', borderRadius: 8 },
  copyPickerCancelText: { textAlign: 'center', color: '#6b7280', fontSize: 14, fontWeight: '600' },
});
